# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    includePreviewVersions: true
- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
- task: DotNetCoreCLI@2
  displayName: 'restore'
  inputs:
    command: restore
    vstsFeed: 'imail/imailfeed'
- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: build
    vstsFeed: 'imail/imailfeed'
- task: DotNetCoreCLI@2
  displayName: publish
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureWebApp@1
  displayName: 'web app publish'
  inputs:
      azureSubscription: '<Azure service connection>'
      appType: 'webAppLinux'
      appName: 'graphazure6'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'